config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  	devise_scope :user do
  		get "sign_in", to: "devise/sessions#new"
  	end

	resources :investors
 	resources :projects

 	get '/search', to: 'projects#index'
  	# post '/login', to: 'sessions#create'
  	# get '/login', to: 'sessions#new'
  	# delete '/logout', to: 'sessions#destroy'

  root 'home#show'
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	validates :name, presence: true, uniqueness:true

	has_many :investor_interests
	has_many :investors, through: :investor_interests
end

app/models/investor.rb
class Investor < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :full_name, presence: true

	has_many :projects, dependent: :destroy
	
	has_many :investor_interests
	has_many :interests, through: :investor_interests

end

app/models/investor_interest.rb
class InvestorInterest < ActiveRecord::Base
	belongs_to :investor
	belongs_to :interest
end

app/models/project.rb
class Project < ActiveRecord::Base
belongs_to :investor

	def self.search(search)
		where("name LIKE ?", "%#{search}%")

	end

end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :full_name, presence: true

	has_many :projects, dependent: :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, on: :create
	validates :password_confirmation, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	private


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	end
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
	before_action :authenticate_user!

	def index
		@investors = Investor.all
	end

	def show
		@investor = Investor.find_by_id(params[:id])
		@projects = @investor.projects
	end

	def new
		@investor = Investor.new
	end

	def edit
		@investor = Investor.find_by_id(params[:id])
	end


	def create
		@investor = Investor.new(investor_params)

		if @investor.save
			redirect_to investor_path(@investor), notice: 'Investor was added successfully'
			
			#redirect_to investors_path(@investor), notice: 'Investor was added successfully'
			#happy path
		else
			flash[:alert] = 'There was an error creating the investor'
			render :new
			#unhappy path
		end
	end

	def update
		@investor = Investor.find_by_id(params[:id])
		# if investor is found
		if @investor.update_attributes(investor_params)
			redirect_to investors_path, notice: 'Investor was updated successfully'
			
		# call update attributes in investor and pass in field valies
		# show flash message confirming the successful update
		else
			flash[:alert]= 'Bad things happened!'
			render :edit
		# redirect to the index page
		# if investor is not found
		end
		# render :edit page with flash message informing user of an error
	end

	def destroy
		@investor = Investor.find_by_id(params[:id])

		if @investor.destroy
			flash[:notice] = "#{@investor.email} was successfully deleted"
		else
			flash[:alert] = "There was an error while attempting to delete this investor"
		end

			redirect_to investors_path
	end

private


def investor_params
	params.require(:investor).permit(:email, :full_name, :phone, :profile, :interest_ids => [])
end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:search].present?
			@projects = Project.search(params[:search])
		else
			@projects = Project.all
		end
	end

	def show
		@project = Project.find_by_id(params[:id])
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find_by_id(params[:id])
	end


	def create
		@project = Project.new(project_params)

		if @project.save
			flash[:notice] = 'Project saved successfully'
			redirect_to project_path(@project)
			#redirect_to projects_path(@project), notice: 'Project was added successfully'
			#happy path
		else
			flash[:alert] = 'There was an error creating the project'
			render :new
			#unhappy path
		end
	end

	def update
		@project = Project.find_by_id(params[:id])
		# if project is found
		if @project.update_attributes(project_params)
			redirect_to projects_path, notice: 'Project was updated successfully'
			
		# call update attributes in project and pass in field valies
		# show flash message confirming the successful update
		else
			flash[:alert]= 'Bad things happened!'
			render :edit
		# redirect to the index page
		# if project is not found
		end
		# render :edit page with flash message informing user of an error
	end

	def destroy
		@project = Project.find_by_id(params[:id])

		if @project.destroy
			flash[:notice] = "#{@project.name} was successfully deleted"
		else
			flash[:alert] = "There was an error while attempting to delete this project"
		end

			redirect_to projects_path
	end

	private

		def project_params
			params.require(:project).permit(:name, :investor_id)
		end


end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
	before_action :authenticate_user!, only: [:destroy]

	def new
	end

	def create
		user = User.find_by(email: params[:email])

		if user && user.authenticate(params[:password])
		session[:user_id] = user.id
		redirect_to :root, notice: "Welcome back #{user.email}!"
		else
			flash[:alert] = "Invalid email or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to :root, notice: "Successfully logged out"
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authorize

	def index
		@students = Student.all
	end

	def show
		@student = Student.find_by_id(params[:id])
		@projects = @student.projects
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find_by_id(params[:id])
	end


	def create
		@student = Student.new(params[:student])

		if @student.save
			redirect_to student_path(@student), notice: 'Student was added successfully'
			
			#redirect_to students_path(@student), notice: 'Student was added successfully'
			#happy path
		else
			flash[:alert] = 'There was an error creating the student'
			render :new
			#unhappy path
		end
	end

	def update
		@student = Student.find_by_id(params[:id])
		# if student is found
		if @student.update_attributes(params[:student])
			redirect_to students_path, notice: 'Student was updated successfully'
			
		# call update attributes in student and pass in field valies
		# show flash message confirming the successful update
		else
			flash[:alert]= 'Bad things happened!'
			render :edit
		# redirect to the index page
		# if student is not found
		end
		# render :edit page with flash message informing user of an error
	end

	def destroy
		@student = Student.find_by_id(params[:id])

		if @student.destroy
			flash[:notice] = "#{@student.email} was successfully deleted"
		else
			flash[:alert] = "There was an error while attempting to delete this student"
		end

			redirect_to students_path
	end

private


# def student_params
# 	params.require(:student).permit(:email, :full_name, :phone, :hero)
# end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def formatted_phone_number(phone)
		return unless phone.present?
		
		number_to_phone(phone, area_code: true)
	end
end

app/views/home/show.html.erb
<h1>Welcome to your Investments Application</h1>

<% if current_user %>
	<ul>
		<li><div><%= link_to "Investor List", investors_path %></div></li>
		<li><div><%= link_to "Project List", projects_path %></div></li>
	</ul>

<% end %>

app/views/investors/_form.html.erb
<div class="row">

	<div class="col-md-6">

		<%= form_for @investor do |f| %>
			<div class='form-group'>
				<%= f.label :email, "Email Address" %>
				<%= f.text_field :email, class: 'form-control'%>
			</div>

			<div class='form-group'>
				<%= f.label :full_name %>
				<%= f.text_field :full_name, class: 'form-control'%> 
			</div>

			<div class='form-group'>
				<%= f.label :phone %>
				<%= f.text_field :phone, class: 'form-control'%>
			</div>

			<div class='form-group'>
				<%= f.label :profile %>
				<%= f.text_field :profile, class: 'form-control'%>
			</div>

		<div class="form-group">
			<%= f.label :interests %><br>
			<%= f.collection_check_boxes :interest_ids, Interest.all, :id, :name do |b| %>
			<%= b.label(:"data-value" => b.value) {b.check_box + "" + b.text} %><br>
			<% end %>
		</div>

		<%= f.submit nil, class: 'btn btn-primary' %>

		<% end %>

	</div>

</div>

app/views/investors/edit.html.erb
<h1>Edit Investor</h1>

<%= render "form" %>

app/views/investors/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>Investor List</h1>
	</div>
</div>

<div class="row">
	<div class="col-md-9">

		<%= link_to "Add new Investor", new_investor_path %>

		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Email</th>
					<th>Investor Name</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @investors.each do |investor| %>
					<tr>
						<td><%= link_to investor.email, investor_path(investor) %></td>
						<td><%= investor.full_name %></td>
						<td><%= button_to "Delete", investor_path(investor), :method=> :delete, :class=> :destroy, :confirm=> "Are you sure?" %></td>
					</tr>
				<% end %>

			</tbody>		
		</table>
	</div>
</div>

app/views/investors/new.html.erb
<h1>Add new Investor</h1>

<%= render "form" %>

app/views/investors/show.html.erb
<h1>Investor Profile</h1>

<%= link_to "Back to Investor List", investors_path %>
<%= link_to "Edit", edit_investor_path(@investor) %>


<h2><span>Email</span>: <%= @investor.email %></h2>
<h2><span>Full Name</span>: <%= @investor.full_name %></h2>
<h2><span>Phone</span>: <%= formatted_phone_number(@investor.phone) %></h2>
<h2><span>Profile</span>: <%= @investor.profile %></h2>
<h2><span>Created</span>: <%= time_ago_in_words(@investor.created_at) %></h2>

<h2> Projects </h2>

<ul>
	<% @projects.each do |project| %>
		<li><%= project.name %></li>
	<% end %>
</ul>

<h2> Interests </h2>

<ul>
	<% @investor.interests.each do |interest| %>
		<li><%= interest.name %></li>
	<% end %>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>

	<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
	<div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://localhost:3000/">Investor Database</a>
    </div>

	<div class="collapse navbar-collapse">

		<ul class="nav navbar-nav navbar-right">
			<% if current_user %>	
		
				<span class="user-email"><%= current_user.email %></span>
				<%= button_to "Logout", destroy_user_session_path, :method=> :delete%>
			<% else %>
				<%= link_to "Login", new_user_session_path %>
			<% end %>		
		</ul>

	</div>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvestmentsApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

	
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br>
	<%= f.collection_select(:investor_id, Investor.all, :id, :full_name, prompt: true) %>

	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

app/views/projects/index.html.erb
<h1>Project List</h1>


<% if current_user %>
	<%= link_to "Add new Project", new_project_path %>
<% end %>

<%= form_tag("/search", method: :get) do %>
	<%= label_tag(:search, "Search") %>
	<%= text_field_tag(:search) %>
	<%= submit_tag("Search") %>
<% end %>

<ul>
	<% @projects.each do |project| %>
		<li>
			
			<span><%= link_to project.name, project_path(project) %></span>

			<% if current_user %>
				<span>
					<%= button_to "Delete", project_path(project), :method=> :delete, :class=> :destroy, data: {confirm: "Are you sure?"} %>
				</span>
			<% end %>


		</li>
	<% end %>
</ul>

app/views/projects/new.html.erb
<h1>Add new Project</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1>Project Profile</h1>

<%= link_to "Back to Project List", projects_path %>
<%= link_to "Edit", edit_project_path(@project) %>

<h2><span>Name</span>: <%= @project.name %></h2>
<h2><span>Created</span>: <%= time_ago_in_words(@project.created_at) %></h2>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<%= f.label :email, "Email Address" %>
	<%= f.text_field :email %> <br>

	<%= f.label :full_name %>
	<%= f.text_field :full_name %> <br>

	<%= f.label :phone %>
	<%= f.text_field :phone %> <br>

	<%= f.label :hero %>
	<%= f.text_field :hero %> <br>

	<%= f.submit %>

<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render "form" %>

app/views/students/index.html.erb
<h1>Student List</h1>


<%= link_to "Add new Student", new_student_path %>

<ul>
	<% @students.each do |student| %>
		<li>
			<span><%= link_to student.email, student_path(student) %></span> |
			<span><%= student.full_name %></span>
			
			<span>
				<%= button_to "Delete", student_path(student), :method=> :delete, :class=> :destroy, :confirm=> "Are you sure?" %>
			</span>
		</li>
	<% end %>
</ul>

app/views/students/new.html.erb
<h1>Add new Student</h1>

<%= render "form" %>

app/views/students/show.html.erb
<h1>Student Profile</h1>

<%= link_to "Back to Student List", students_path %>
<%= link_to "Edit", edit_student_path(@student) %>


<h2><span>Email</span>: <%= @student.email %></h2>
<h2><span>Full Name</span>: <%= @student.full_name %></h2>
<h2><span>Phone</span>: <%= formatted_phone_number(@student.phone) %></h2>
<h2><span>Hero Name</span>: <%= @student.hero %></h2>
<h2><span>Created</span>: <%= time_ago_in_words(@student.created_at) %></h2>

<h2> Projects </h2>

<ul>
	<% @projects.each do |project| %>
		<li><%= project.name %></li>
	<% end %>
</ul>